# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.15.0
    container_name: www
    restart: unless-stopped
    build: .
    # uncomment these if you are having this issue with the build:
    # /usr/local/bundle/gems/jekyll-4.3.4/lib/jekyll/site.rb:509:in `initialize': Permission denied @ rb_sysopen - /srv/jekyll/.jekyll-cache/.gitignore (Errno::EACCES)
    # and fill the args values with the output of the commands on the right
    # build:
    #   args:
    #     GROUPID: # id -g
    #     GROUPNAME: # id -gn
    #     USERID: # id -u
    #     USERNAME: # echo $USER
    ports:
      - 82:8080
      # - 35729:35729
    volumes:
      - /mnt/naspool/home/seonghoon/www:/srv/jekyll
    environment:
      - JEKYLL_ENV=production
